jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4

      - name: Clone another public repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          depth: 1
          branch: 'main'
          owner: 'sudarsanchakri123'
          repository: 'develop-the-app'

      - name: Move into cloned repo
        run: |
          cd develop-the-app   # move into the cloned repo
          ls -l                # list files inside
